apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-db.fullname" . }}
  labels:
    {{- include "orders-db.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "orders-db.selectorLabels" . | nindent 4 }}
