apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "load-testing.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "load-testing.labels" . | nindent 4 }}
spec:
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "load-testing.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: "TARGET_URL"
                  value: "http://idir-front-end"
          restartPolicy: {{ .Values.restartPolicy }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
