apiVersion: v1
kind: Service
metadata:
  name: {{ include "front-end.fullname" . }}
  labels:
    {{- include "front-end.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "front-end.selectorLabels" . | nindent 4 }}
